### ISSUE TITLE
Push to GitLab action fails

### ISSUE THREAD

**Issue by halirutan** [yigbt/deepFPlearn#8]
Originally, the idea was that we work on the GitHub repo and push automatically to the UFZ Gitlab, because since recently @halirutan could not get access to those GitLab repos.  I believe Julienne did something to bring the repos out of sync and now the "push to GitLab" action fails.

Matthias (or Julienne), could you take a look and fix it?

**Comment by bernt-matthias** [comment]
Hi @halirutan I guess we either solves this by force pushing (https://github.com/yigbt/deepFPlearn/pull/9) or try the more elegant solution outlined eg. here: https://jsramblings.com/automatically-sync-gitlab-mirrored-repository-on-every-push-to-github/

**Comment by bernt-matthias** [comment]
See also here https://docs.gitlab.com/ee/user/project/repository/mirror/index.html

**Comment by bernt-matthias** [comment]
gitlab pull sync with webhooks ist Premium-Feature .. also nicht verfuegbar

https://github.com/marketplace/actions/mirror-to-gitlab-and-run-gitlab-ci

**Comment by halirutan** [comment]
Yep, read the mail. What do we do? Suggestions?

**Comment by bernt-matthias** [comment]
I wait for Sebastian to answer. Will meet him latest tomorrow in the Dept. seminar.
